# ============================================================
#  data.py — Datos estáticos MMJ Tournament Hub
# ============================================================

POS_COLORS = {
    "GK":  "#f59e0b",
    "DEF": "#3b82f6",
    "MID": "#22c55e",
    "FWD": "#ef4444",
}

PLAYER_DATA = {
    "U. Simón":             {"pos": "GK",     "nat": "es",     "sofifa": 230869},
    "J. Musiala":           {"pos": "MID",    "nat": "de",     "sofifa": 256790},
    "Rodrygo":              {"pos": "FWD",    "nat": "br",     "sofifa": 243812},
    "J. Brandt":            {"pos": "MID",    "nat": "de",     "sofifa": 212194},
    "P. Dybala":            {"pos": "FWD",    "nat": "ar",     "sofifa": 211110},
    "K. Mbappé":            {"pos": "FWD",    "nat": "fr",     "sofifa": 231747},
    "P. Hincapié":          {"pos": "DEF",    "nat": "ec",     "sofifa": 256197},
    "N. Madueke":           {"pos": "FWD",    "nat": "gb-eng", "sofifa": 254796},
    "J. Enciso":            {"pos": "FWD",    "nat": "py",     "sofifa": 255434},
    "Y. Asprilla":          {"pos": "FWD",    "nat": "co",     "sofifa": 271464},
    "Ederson":              {"pos": "GK",     "nat": "br",     "sofifa": 210257},
    "J. Tah":               {"pos": "DEF",    "nat": "de",     "sofifa": 213331},
    "L. Messi":             {"pos": "FWD",    "nat": "ar",     "sofifa": 158023},
    "E. Haaland":           {"pos": "FWD",    "nat": "no",     "sofifa": 239085},
    "J. Bynoe-Gittens":     {"pos": "FWD",    "nat": "gb-eng", "sofifa": 266032},
    "G. Puerta":            {"pos": "MID",    "nat": "co",     "sofifa": 273827},
    "O. Bobb":              {"pos": "MID",    "nat": "no",     "sofifa": 277295},
    "J. Durán":             {"pos": "FWD",    "nat": "co",     "sofifa": 247172},
    "G. Mamardashvili":     {"pos": "GK",     "nat": "ge",     "sofifa": 262621},
    "F. Kessié":            {"pos": "MID",    "nat": "ci",     "sofifa": 230938},
    "Raphinha":             {"pos": "FWD",    "nat": "br",     "sofifa": 233419},
    "M. Llorente":          {"pos": "MID",    "nat": "es",     "sofifa": 226161},
    "J. Maddison":          {"pos": "MID",    "nat": "gb-eng", "sofifa": 220697},
    "Moleiro":              {"pos": "MID",    "nat": "es",     "sofifa": 264388},
    "Nico González":        {"pos": "MID",    "nat": "es",     "sofifa": 255069},
    "Fermín":               {"pos": "MID",    "nat": "es",     "sofifa": 277179},
    "Marc Guiu":            {"pos": "FWD",    "nat": "es",     "sofifa": 278813},
    "N. Pope":              {"pos": "GK",     "nat": "gb-eng", "sofifa": 203841},
    "R. Andrich":           {"pos": "MID",    "nat": "de",     "sofifa": 212242},
    "R. Mahrez":            {"pos": "FWD",    "nat": "dz",     "sofifa": 204485},
    "Nico Williams":        {"pos": "FWD",    "nat": "es",     "sofifa": 256516},
    "D. Malen":             {"pos": "FWD",    "nat": "nl",     "sofifa": 231447},
    "R. Gravenberch":       {"pos": "MID",    "nat": "nl",     "sofifa": 246104},
    "T. Lamptey":           {"pos": "DEF",    "nat": "gh",     "sofifa": 242418},
    "A. Pavlovic":          {"pos": "MID",    "nat": "de",     "sofifa": 275298},
    "K. Gordon":            {"pos": "FWD",    "nat": "gb-eng", "sofifa": 260406},
    "G. Ochoa":             {"pos": "GK",     "nat": "mx",     "sofifa": 140233},
    "João Cancelo":         {"pos": "DEF",    "nat": "pt",     "sofifa": 210514},
    "H. Kane":              {"pos": "FWD",    "nat": "gb-eng", "sofifa": 202126},
    "M. Olise":             {"pos": "FWD",    "nat": "fr",     "sofifa": 247827},
    "C. Lukeba":            {"pos": "DEF",    "nat": "fr",     "sofifa": 262138},
    "T. Gulliksen":         {"pos": "FWD",    "nat": "no",     "sofifa": 247025},
    "R. Bardghji":          {"pos": "FWD",    "nat": "se",     "sofifa": 265600},
    "M. Maignan":           {"pos": "GK",     "nat": "fr",     "sofifa": 215698},
    "N. Schlotterbeck":     {"pos": "DEF",    "nat": "de",     "sofifa": 247819},
    "F. Torres":            {"pos": "FWD",    "nat": "es",     "sofifa": 241461},
    "L. Díaz":              {"pos": "FWD",    "nat": "co",     "sofifa": 241084},
    "A. Davies":            {"pos": "DEF",    "nat": "ca",     "sofifa": 234396},
    "L. Romero":            {"pos": "MID",    "nat": "ar",     "sofifa": 258467},
    "A. Scott":             {"pos": "DEF",    "nat": "gb-eng", "sofifa": 261299},
    "Pau Cubarsí":          {"pos": "DEF",    "nat": "es",     "sofifa": 278046},
    "J. Duranville":        {"pos": "FWD",    "nat": "be",     "sofifa": 262105},
    "M. Neuer":             {"pos": "GK",     "nat": "de",     "sofifa": 167495},
    "E. Tapsoba":           {"pos": "DEF",    "nat": "bf",     "sofifa": 247263},
    "Pedri":                {"pos": "MID",    "nat": "es",     "sofifa": 251854},
    "L. Sané":              {"pos": "FWD",    "nat": "de",     "sofifa": 222492},
    "A. Hložek":            {"pos": "FWD",    "nat": "cz",     "sofifa": 246618},
    "Fábio Carvalho":       {"pos": "MID",    "nat": "pt",     "sofifa": 256725},
    "Y. Eduardo":           {"pos": "FWD",    "nat": "nl",     "sofifa": 0},
    "O. Diomande":          {"pos": "DEF",    "nat": "ci",     "sofifa": 270531},
    "L. Hrádecký":          {"pos": "GK",     "nat": "fi",     "sofifa": 190941},
    "R. James":             {"pos": "DEF",    "nat": "gb-eng", "sofifa": 238074},
    "D. Szoboszlai":        {"pos": "MID",    "nat": "hu",     "sofifa": 236772},
    "J. Álvarez":           {"pos": "FWD",    "nat": "ar",     "sofifa": 246191},
    "S. Gnabry":            {"pos": "FWD",    "nat": "de",     "sofifa": 206113},
    "H. Elliott":           {"pos": "MID",    "nat": "gb-eng", "sofifa": 261275},
    "F. Pellistri":         {"pos": "FWD",    "nat": "uy",     "sofifa": 253283},
    "Marc Casadó":          {"pos": "MID",    "nat": "es",     "sofifa": 272600},
    "B. Domínguez":         {"pos": "FWD",    "nat": "ar",     "sofifa": 269558},
    "G. Rulli":             {"pos": "GK",     "nat": "ar",     "sofifa": 215316},
    "N. Barella":           {"pos": "MID",    "nat": "it",     "sofifa": 224232},
    "H. Son":               {"pos": "FWD",    "nat": "kr",     "sofifa": 200104},
    "Vini Jr.":             {"pos": "FWD",    "nat": "br",     "sofifa": 238794},
    "Marquinhos":           {"pos": "DEF",    "nat": "br",     "sofifa": 207865},
    "R. Lewis":             {"pos": "DEF",    "nat": "gb-eng", "sofifa": 271574},
    "E. Millot":            {"pos": "MID",    "nat": "fr",     "sofifa": 252259},
    "V. Barco":             {"pos": "FWD",    "nat": "ar",     "sofifa": 263370},
    "B. Doak":              {"pos": "FWD",    "nat": "gb-sct", "sofifa": 266815},
    "J. Oblak":             {"pos": "GK",     "nat": "si",     "sofifa": 200389},
    "R. Sterling":          {"pos": "FWD",    "nat": "gb-eng", "sofifa": 202652},
    "İ. Gündoğan":          {"pos": "MID",    "nat": "de",     "sofifa": 186942},
    "K. Kvaratskhelia":     {"pos": "FWD",    "nat": "ge",     "sofifa": 247635},
    "X. Simons":            {"pos": "MID",    "nat": "nl",     "sofifa": 245367},
    "L. Badé":              {"pos": "DEF",    "nat": "fr",     "sofifa": 255106},
    "P. Wanner":            {"pos": "MID",    "nat": "de",     "sofifa": 266237},
    "P. Brunner":           {"pos": "DEF",    "nat": "de",     "sofifa": 274126},
    "A. Lopes":             {"pos": "GK",     "nat": "pt",     "sofifa": 199482},
    "A. Rüdiger":           {"pos": "DEF",    "nat": "de",     "sofifa": 205452},
    "F. Valverde":          {"pos": "MID",    "nat": "uy",     "sofifa": 239053},
    "T. Kubo":              {"pos": "FWD",    "nat": "jp",     "sofifa": 237681},
    "K. Benzema":           {"pos": "FWD",    "nat": "fr",     "sofifa": 165153},
    "J. Doku":              {"pos": "FWD",    "nat": "be",     "sofifa": 246420},
    "Yeremy Pino":          {"pos": "FWD",    "nat": "es",     "sofifa": 259377},
    "A. Gray":              {"pos": "FWD",    "nat": "gb-eng", "sofifa": 270208},
    "A. Gómez":             {"pos": "MID",    "nat": "co",     "sofifa": 266674},
    "P. Gulácsi":           {"pos": "GK",     "nat": "hu",     "sofifa": 185122},
    "A. Rabiot":            {"pos": "MID",    "nat": "fr",     "sofifa": 210008},
    "M. Depay":             {"pos": "FWD",    "nat": "nl",     "sofifa": 202556},
    "J. Koundé":            {"pos": "DEF",    "nat": "fr",     "sofifa": 241486},
    "A. Balde":             {"pos": "DEF",    "nat": "es",     "sofifa": 263578},
    "A. Ezzalzouli":        {"pos": "FWD",    "nat": "ma",     "sofifa": 264432},
    "D. Moreira":           {"pos": "MID",    "nat": "pt",     "sofifa": 270039},
    "L. Miley":             {"pos": "MID",    "nat": "gb-eng", "sofifa": 274246},
    "M. ter Stegen":        {"pos": "GK",     "nat": "de",     "sofifa": 192448},
    "V. van Dijk":          {"pos": "DEF",    "nat": "nl",     "sofifa": 203376},
    "L. Modrić":            {"pos": "MID",    "nat": "hr",     "sofifa": 177003},
    "Rafael Leão":          {"pos": "FWD",    "nat": "pt",     "sofifa": 241721},
    "J. Frimpong":          {"pos": "DEF",    "nat": "nl",     "sofifa": 253149},
    "K. Coman":             {"pos": "FWD",    "nat": "fr",     "sofifa": 213345},
    "P. Barrios":           {"pos": "MID",    "nat": "es",     "sofifa": 272449},
    "N. Zalewski":          {"pos": "MID",    "nat": "pl",     "sofifa": 262113},
    "Á. Alarcón":           {"pos": "MID",    "nat": "es",     "sofifa": 0},
    "G. Scalvini":          {"pos": "DEF",    "nat": "it",     "sofifa": 265188},
    "T. Courtois":          {"pos": "GK",     "nat": "be",     "sofifa": 192119},
    "Kim Min Jae":          {"pos": "DEF",    "nat": "kr",     "sofifa": 237086},
    "F. de Jong":           {"pos": "MID",    "nat": "nl",     "sofifa": 228702},
    "T. Alexander-Arnold":  {"pos": "DEF",    "nat": "gb-eng", "sofifa": 231281},
    "H. Ekitike":           {"pos": "FWD",    "nat": "fr",     "sofifa": 257289},
    "C. Medina":            {"pos": "MID",    "nat": "ar",     "sofifa": 261082},
    "Afonso Moreira":       {"pos": "DEF",    "nat": "pt",     "sofifa": 276901},
    "M. Tel":               {"pos": "FWD",    "nat": "fr",     "sofifa": 268421},
    "A. Onana":             {"pos": "GK",     "nat": "cm",     "sofifa": 226753},
    "A. Laporte":           {"pos": "DEF",    "nat": "es",     "sofifa": 212218},
    "V. Osimhen":           {"pos": "FWD",    "nat": "ng",     "sofifa": 232293},
    "R. Araujo":            {"pos": "DEF",    "nat": "uy",     "sofifa": 246340},
    "João Félix":           {"pos": "FWD",    "nat": "pt",     "sofifa": 242444},
    "Stefan Bajcetic":      {"pos": "MID",    "nat": "es",     "sofifa": 271975},
    "L. Abada":             {"pos": "FWD",    "nat": "il",     "sofifa": 263377},
    "C. Bradley":           {"pos": "DEF",    "nat": "gg",     "sofifa": 264298},
    "C. Cassano":           {"pos": "MID",    "nat": "it",     "sofifa": 0},
    "Alisson":              {"pos": "GK",     "nat": "br",     "sofifa": 212831},
    "Casemiro":             {"pos": "MID",    "nat": "br",     "sofifa": 200145},
    "C. Nkunku":            {"pos": "FWD",    "nat": "fr",     "sofifa": 232411},
    "Rúben Dias":           {"pos": "DEF",    "nat": "pt",     "sofifa": 239818},
    "Neymar Jr":            {"pos": "FWD",    "nat": "br",     "sofifa": 190871},
    "G. Reyna":             {"pos": "MID",    "nat": "us",     "sofifa": 245541},
    "B. Castro":            {"pos": "MID",    "nat": "co",     "sofifa": 271549},
    "O. Cortés":            {"pos": "MID",    "nat": "co",     "sofifa": 266673},
    "K. Páez":              {"pos": "MID",    "nat": "ec",     "sofifa": 274559},
    "K. Navas":             {"pos": "GK",     "nat": "cr",     "sofifa": 0},
    "M. de Ligt":           {"pos": "DEF",    "nat": "nl",     "sofifa": 235243},
    "N. Okafor":            {"pos": "FWD",    "nat": "ch",     "sofifa": 242530},
    "J. Bellingham":        {"pos": "MID",    "nat": "gb-eng", "sofifa": 252371},
    "T. Baldanzi":          {"pos": "MID",    "nat": "it",     "sofifa": 269312},
    "Talles Magno":         {"pos": "FWD",    "nat": "br",     "sofifa": 0},
    "E. Mbappé":            {"pos": "FWD",    "nat": "fr",     "sofifa": 278172},
    "I. Babadi":            {"pos": "MID",    "nat": "nl",     "sofifa": 277465},
    "Y. Bounou":            {"pos": "GK",     "nat": "ma",     "sofifa": 209981},
    "N. Süle":              {"pos": "DEF",    "nat": "de",     "sofifa": 212190},
    "Diogo Jota":           {"pos": "FWD",    "nat": "pt",     "sofifa": 0},
    "M. Ødegaard":          {"pos": "MID",    "nat": "no",     "sofifa": 222665},
    "A. Meret":             {"pos": "GK",     "nat": "it",     "sofifa": 225116},
    "O. Dembélé":           {"pos": "FWD",    "nat": "fr",     "sofifa": 231443},
    "Gonçalo Inácio":       {"pos": "DEF",    "nat": "pt",     "sofifa": 257179},
    "S. Magassa":           {"pos": "DEF",    "nat": "fr",     "sofifa": 275102},
    "R. Cherki":            {"pos": "MID",    "nat": "fr",     "sofifa": 251570},
    "B. Norton-Cuffy":      {"pos": "DEF",    "nat": "gb-eng", "sofifa": 260653},
    "G. Donnarumma":        {"pos": "GK",     "nat": "it",     "sofifa": 230621},
    "Éder Militão":         {"pos": "DEF",    "nat": "br",     "sofifa": 240130},
    "Á. Di María":          {"pos": "FWD",    "nat": "ar",     "sofifa": 183898},
    "Rodri":                {"pos": "MID",    "nat": "es",     "sofifa": 231866},
    "J. Grealish":          {"pos": "FWD",    "nat": "gb-eng", "sofifa": 206517},
    "N. Rovella":           {"pos": "MID",    "nat": "it",     "sofifa": 255001},
    "D. Udogie":            {"pos": "DEF",    "nat": "it",     "sofifa": 259583},
    "D. Washington":        {"pos": "MID",    "nat": "us",     "sofifa": 0},
    "Ângelo":               {"pos": "FWD",    "nat": "br",     "sofifa": 272829},
    "E. Martínez":          {"pos": "GK",     "nat": "ar",     "sofifa": 202811},
    "S. Milinković-Savić":  {"pos": "MID",    "nat": "rs",     "sofifa": 223848},
    "Bruno Fernandes":      {"pos": "MID",    "nat": "pt",     "sofifa": 212198},
    "S. Chukwueze":         {"pos": "FWD",    "nat": "ng",     "sofifa": 246172},
    "R. Lewandowski":       {"pos": "FWD",    "nat": "pl",     "sofifa": 188545},
    "D. Alaba":             {"pos": "DEF",    "nat": "at",     "sofifa": 197445},
    "Antony":               {"pos": "FWD",    "nat": "br",     "sofifa": 255475},
    "R. Højlund":           {"pos": "FWD",    "nat": "dk",     "sofifa": 259399},
    "T. Pembélé":           {"pos": "DEF",    "nat": "fr",     "sofifa": 257270},
    "Y. Moukoko":           {"pos": "FWD",    "nat": "de",     "sofifa": 240833},
    "Matheus França":       {"pos": "MID",    "nat": "br",     "sofifa": 265420},
    "M. Flekken":           {"pos": "GK",     "nat": "nl",     "sofifa": 211738},
    "Brahim":               {"pos": "MID",    "nat": "es",     "sofifa": 231410},
    "S. Mané":              {"pos": "FWD",    "nat": "sn",     "sofifa": 208722},
    "E. Fernández":         {"pos": "MID",    "nat": "ar",     "sofifa": 247090},
    "Bernardo Silva":       {"pos": "MID",    "nat": "pt",     "sofifa": 218667},
    "C. Palmer":            {"pos": "MID",    "nat": "gb-eng", "sofifa": 257534},
    "A. Velasco":           {"pos": "FWD",    "nat": "es",     "sofifa": 252238},
    "K. Yıldız":            {"pos": "FWD",    "nat": "tr",     "sofifa": 277954},
    "S. Charles":           {"pos": "MID",    "nat": "gg",     "sofifa": 276695},
    "W. Szczęsny":          {"pos": "GK",     "nat": "pl",     "sofifa": 186153},
    "F. Tomori":            {"pos": "DEF",    "nat": "gb-eng", "sofifa": 232756},
    "J. Kimmich":           {"pos": "MID",    "nat": "de",     "sofifa": 212622},
    "L. Martínez":          {"pos": "FWD",    "nat": "ar",     "sofifa": 231478},
    "Gavi":                 {"pos": "MID",    "nat": "es",     "sofifa": 264240},
    "Vitor Roque":          {"pos": "FWD",    "nat": "br",     "sofifa": 0},
    "Héctor Fort":          {"pos": "DEF",    "nat": "es",     "sofifa": 278923},
    "I. Fresneda":          {"pos": "DEF",    "nat": "es",     "sofifa": 266253},
    "G. Kobel":             {"pos": "GK",     "nat": "ch",     "sofifa": 235073},
    "K. Trippier":          {"pos": "DEF",    "nat": "gb-eng", "sofifa": 186345},
    "G. Martinelli":        {"pos": "FWD",    "nat": "br",     "sofifa": 251566},
    "K. Havertz":           {"pos": "MID",    "nat": "de",     "sofifa": 235790},
    "L. Goretzka":          {"pos": "MID",    "nat": "de",     "sofifa": 209658},
    "F. Chiesa":            {"pos": "FWD",    "nat": "it",     "sofifa": 235805},
    "Ansu Fati":            {"pos": "FWD",    "nat": "es",     "sofifa": 253004},
    "A. Kalimuendo":        {"pos": "FWD",    "nat": "fr",     "sofifa": 253444},
    "S. Pafundi":           {"pos": "MID",    "nat": "it",     "sofifa": 271575},
    "D. Doué":              {"pos": "FWD",    "nat": "fr",     "sofifa": 271421},
    "J. Pickford":          {"pos": "GK",     "nat": "gb-eng", "sofifa": 204935},
    "Sergio Ramos":         {"pos": "DEF",    "nat": "es",     "sofifa": 0},
    "H. Lozano":            {"pos": "FWD",    "nat": "mx",     "sofifa": 221992},
    "K. Adeyemi":           {"pos": "FWD",    "nat": "de",     "sofifa": 251852},
    "M. Hummels":           {"pos": "DEF",    "nat": "de",     "sofifa": 0},
    "António Silva":        {"pos": "DEF",    "nat": "pt",     "sofifa": 270086},
    "M. Thiaw":             {"pos": "DEF",    "nat": "de",     "sofifa": 256261},
    "C. Chukwuemeka":       {"pos": "MID",    "nat": "gb-eng", "sofifa": 259356},
    "B. El Khannouss":      {"pos": "MID",    "nat": "ma",     "sofifa": 257504},
    "Y. Sommer":            {"pos": "GK",     "nat": "ch",     "sofifa": 177683},
    "T. Hernández":         {"pos": "DEF",    "nat": "fr",     "sofifa": 232656},
    "B. Saka":              {"pos": "FWD",    "nat": "gb-eng", "sofifa": 246669},
    "K. De Bruyne":         {"pos": "MID",    "nat": "be",     "sofifa": 192985},
    "M. Salah":             {"pos": "FWD",    "nat": "eg",     "sofifa": 209331},
    "K. Casteels":          {"pos": "GK",     "nat": "be",     "sofifa": 192984},
    "J. Castrop":           {"pos": "MID",    "nat": "de",     "sofifa": 264194},
    "B. Brobbey":           {"pos": "FWD",    "nat": "nl",     "sofifa": 258513},
    "M. Soulé":             {"pos": "MID",    "nat": "ar",     "sofifa": 265695},
    "W. Zaïre-Emery":       {"pos": "MID",    "nat": "fr",     "sofifa": 270673},
    "A. Ramsdale":          {"pos": "GK",     "nat": "gb-eng", "sofifa": 233934},
    "K. Walker":            {"pos": "DEF",    "nat": "gb-eng", "sofifa": 188377},
    "M. Diaby":             {"pos": "FWD",    "nat": "fr",     "sofifa": 241852},
    "C. Gakpo":             {"pos": "FWD",    "nat": "nl",     "sofifa": 242516},
    "P. Foden":             {"pos": "MID",    "nat": "gb-eng", "sofifa": 237692},
    "A. Lafont":            {"pos": "GK",     "nat": "fr",     "sofifa": 231691},
    "B. Barcola":           {"pos": "FWD",    "nat": "fr",     "sofifa": 264652},
    "Q. Sullivan":          {"pos": "MID",    "nat": "us",     "sofifa": 260547},
    "Iker Bravo":           {"pos": "FWD",    "nat": "es",     "sofifa": 265194},
    "T. Land":              {"pos": "DEF",    "nat": "nl",     "sofifa": 275411},
    "É. Mendy":             {"pos": "GK",     "nat": "sn",     "sofifa": 234642},
    "A. Griezmann":         {"pos": "FWD",    "nat": "fr",     "sofifa": 194765},
    "L. Paqueta":           {"pos": "MID",    "nat": "br",     "sofifa": 233927},
    "Grimaldo":             {"pos": "DEF",    "nat": "es",     "sofifa": 210035},
    "A. Hakimi":            {"pos": "DEF",    "nat": "ma",     "sofifa": 235212},
    "M. Rashford":          {"pos": "FWD",    "nat": "gb-eng", "sofifa": 231677},
    "A. Correa":            {"pos": "FWD",    "nat": "ar",     "sofifa": 214997},
    "Sávio":                {"pos": "FWD",    "nat": "br",     "sofifa": 270409},
    "A. Richardson":        {"pos": "MID",    "nat": "ma",     "sofifa": 262236},
    "C. Echeverri":         {"pos": "FWD",    "nat": "ar",     "sofifa": 276528},
    "J. Hato":              {"pos": "DEF",    "nat": "nl",     "sofifa": 272978},
    "Diogo Costa":          {"pos": "GK",     "nat": "pt",     "sofifa": 234577},
    "Gabriel":              {"pos": "DEF",    "nat": "br",     "sofifa": 232580},
    "Cristiano Ronaldo":    {"pos": "FWD",    "nat": "pt",     "sofifa": 0},
    "A. Robertson":         {"pos": "DEF",    "nat": "gb-sct", "sofifa": 216267},
    "Peter":                {"pos": "MID",    "nat": "br",     "sofifa": 266136},
    "K. Mainoo":            {"pos": "MID",    "nat": "gb-eng", "sofifa": 269136},
    "V. Carboni":           {"pos": "MID",    "nat": "ar",     "sofifa": 272602},
    "A. van Axel Dongen":   {"pos": "DEF",    "nat": "nl",     "sofifa": 266448},
    "H. Lloris":            {"pos": "GK",     "nat": "fr",     "sofifa": 167948},
    "Gabriel Jesús":        {"pos": "FWD",    "nat": "br",     "sofifa": 230666},
    "N. Kanté":             {"pos": "MID",    "nat": "fr",     "sofifa": 215914},
    "G. Xhaka":             {"pos": "MID",    "nat": "ch",     "sofifa": 199503},
    "S. Haller":            {"pos": "FWD",    "nat": "ci",     "sofifa": 205693},
    "A. Garnacho":          {"pos": "FWD",    "nat": "ar",     "sofifa": 268438},
    "M. Kerkez":            {"pos": "DEF",    "nat": "hu",     "sofifa": 260908},
    "M. Del Blanco":        {"pos": "DEF",    "nat": "ar",     "sofifa": 273028},
    "Y. Bonny":             {"pos": "FWD",    "nat": "fr",     "sofifa": 259565},
    "Alex Remiro":          {"pos": "GK",     "nat": "es",     "sofifa": 227127},
    "D. Silva":             {"pos": "MID",    "nat": "es",     "sofifa": 0},
    "D. Rice":              {"pos": "MID",    "nat": "gb-eng", "sofifa": 234378},
    "R. Kolo Muani":        {"pos": "FWD",    "nat": "fr",     "sofifa": 237679},
    "F. Wirtz":             {"pos": "MID",    "nat": "de",     "sofifa": 256630},
    "A. Güler":             {"pos": "MID",    "nat": "tr",     "sofifa": 264309},
    "M. Caicedo":           {"pos": "MID",    "nat": "ec",     "sofifa": 256079},
    "Newerton":             {"pos": "FWD",    "nat": "br",     "sofifa": 277194},
    "E. Ferguson":          {"pos": "FWD",    "nat": "ie",     "sofifa": 259608},
}

# ── Composición de equipos ───────────────────────────────────
TEAM_COMPOSITIONS = {
    "LAFC": {"name": "Los Angeles FC",        "logo": "https://a.espncdn.com/guid/090bf04b-bafb-ac27-0cc5-3fee8a7375ca/logos/primary_logo_on_black_color.png",  "players": ["U. Simón","J. Musiala","Rodrygo","J. Brandt","P. Dybala","K. Mbappé","P. Hincapié","N. Madueke","J. Enciso","Y. Asprilla"]},
    "SEA":  {"name": "Seattle Sounders",       "logo": "https://a.espncdn.com/guid/c847331a-0291-a79c-5b8e-22416f8fe26a/logos/primary_logo_on_black_color.png",  "players": ["Ederson","J. Tah","L. Messi","E. Haaland","J. Bynoe-Gittens","G. Puerta","O. Bobb","J. Durán"]},
    "MIN":  {"name": "Minnesota United",       "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/17362.png",                                  "players": ["G. Mamardashvili","F. Kessié","Raphinha","M. Llorente","J. Maddison","Moleiro","Nico González","Fermín","Marc Guiu"]},
    "VAN":  {"name": "Vancouver Whitecaps",    "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/9727.png",                                   "players": ["N. Pope","R. Andrich","R. Mahrez","Nico Williams","D. Malen","R. Gravenberch","T. Lamptey","A. Pavlovic","K. Gordon"]},
    "COL":  {"name": "Colorado Rapids",        "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/184.png",                                                    "players": ["G. Ochoa","João Cancelo","H. Kane","M. Olise","C. Lukeba","T. Gulliksen","R. Bardghji"]},
    "NHS":  {"name": "Nashville SC",           "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/18986.png",                                                  "players": ["M. Maignan","N. Schlotterbeck","F. Torres","L. Díaz","A. Davies","L. Romero","A. Scott","Pau Cubarsí","J. Duranville"]},
    "CLB":  {"name": "Columbus Crew",          "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/183.png",                                    "players": ["M. Neuer","E. Tapsoba","Pedri","L. Sané","A. Hložek","Fábio Carvalho","Y. Eduardo","O. Diomande"]},
    "SDFC": {"name": "San Diego FC",           "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/22529.png",                                  "players": ["L. Hrádecký","R. James","D. Szoboszlai","J. Álvarez","S. Gnabry","H. Elliott","F. Pellistri","Marc Casadó","B. Domínguez"]},
    "ATX":  {"name": "Austin FC",              "logo": "https://a.espncdn.com/guid/ea2b097a-74d8-3164-b55e-7fd490d63b46/logos/primary_logo_on_primary_color.png", "players": ["G. Rulli","N. Barella","H. Son","Vini Jr.","Marquinhos","R. Lewis","E. Millot","V. Barco","B. Doak"]},
    "CHI":  {"name": "Chicago Fire",           "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/182.png",                                                    "players": ["J. Oblak","R. Sterling","İ. Gündoğan","K. Kvaratskhelia","X. Simons","L. Badé","P. Wanner","P. Brunner"]},
    "NE":   {"name": "New England Revolution", "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/189.png",                                    "players": ["A. Lopes","A. Rüdiger","F. Valverde","T. Kubo","K. Benzema","J. Doku","Yeremy Pino","A. Gray","A. Gómez"]},
    "ORL":  {"name": "Orlando City",           "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/12011.png",                                  "players": ["P. Gulácsi","A. Rabiot","M. Depay","J. Koundé","A. Balde","A. Ezzalzouli","D. Moreira","L. Miley"]},
    "LA":   {"name": "LA Galaxy",              "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/187.png",                                    "players": ["M. ter Stegen","V. van Dijk","L. Modrić","Rafael Leão","J. Frimpong","K. Coman","P. Barrios","N. Zalewski","Á. Alarcón","G. Scalvini"]},
    "SKC":  {"name": "Sporting KC",            "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Sporting_Kansas_City_logo.svg/1280px-Sporting_Kansas_City_logo.svg.png", "players": ["T. Courtois","Kim Min Jae","F. de Jong","T. Alexander-Arnold","H. Ekitike","C. Medina","Afonso Moreira","M. Tel"]},
    "CLT":  {"name": "Charlotte FC",           "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/21300.png&h=200&w=200",                      "players": ["A. Onana","A. Laporte","V. Osimhen","R. Araujo","João Félix","Stefan Bajcetic","L. Abada","C. Bradley","C. Cassano"]},
    "MIA":  {"name": "Inter Miami",            "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/20232.png",                                  "players": ["Alisson","Casemiro","C. Nkunku","Rúben Dias","Neymar Jr","G. Reyna","B. Castro","O. Cortés","K. Páez"]},
    "NYC":  {"name": "New York City FC",       "logo": "https://a.espncdn.com/guid/d902d6f8-8673-29e3-15d9-3ef4c12ce9d0/logos/primary_logo_on_primary_color.png", "players": ["K. Navas","M. de Ligt","N. Okafor","J. Bellingham","T. Baldanzi","Talles Magno","E. Mbappé","I. Babadi"]},
    "RSL":  {"name": "Real Salt Lake",         "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/4771.png",                                   "players": ["Y. Bounou","N. Süle","Diogo Jota","M. Ødegaard","A. Meret","O. Dembélé","Gonçalo Inácio","S. Magassa","R. Cherki","B. Norton-Cuffy"]},
    "TOR":  {"name": "Toronto FC",             "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/7318.png",                                                   "players": ["G. Donnarumma","Éder Militão","Á. Di María","Rodri","J. Grealish","N. Rovella","D. Udogie","D. Washington","Ângelo"]},
    "MTL":  {"name": "CF Montreal",            "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/9720.png",                                   "players": ["E. Martínez","S. Milinković-Savić","Bruno Fernandes","S. Chukwueze","R. Lewandowski","D. Alaba","Antony","R. Højlund","T. Pembélé","Y. Moukoko","Matheus França"]},
    "DAL":  {"name": "FC Dallas",              "logo": "https://a.espncdn.com/guid/fa2f128b-c698-3d43-2910-5561f4442748/logos/primary_logo_on_primary_color.png", "players": ["M. Flekken","Brahim","S. Mané","E. Fernández","Bernardo Silva","C. Palmer","A. Velasco","K. Yıldız","S. Charles"]},
    "POR":  {"name": "Portland Timbers",       "logo": "https://a.espncdn.com/guid/67f3641d-0e73-f4c3-39ca-e0ad4020d315/logos/secondary_logo_on_black_color.png", "players": ["W. Szczęsny","F. Tomori","J. Kimmich","L. Martínez","Gavi","Vitor Roque","Héctor Fort","I. Fresneda"]},
    "HOU":  {"name": "Houston Dynamo",         "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/6077.png",                                   "players": ["G. Kobel","K. Trippier","G. Martinelli","K. Havertz","L. Goretzka","F. Chiesa","Ansu Fati","A. Kalimuendo","S. Pafundi","D. Doué"]},
    "STL":  {"name": "St. Louis City",         "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/21812.png",                                  "players": ["J. Pickford","Sergio Ramos","H. Lozano","K. Adeyemi","M. Hummels","António Silva","M. Thiaw","C. Chukwuemeka","B. El Khannouss"]},
    "ATL":  {"name": "Atlanta United",         "logo": "https://a.espncdn.com/i/teamlogos/soccer/500-dark/18418.png",                                             "players": ["Y. Sommer","T. Hernández","B. Saka","K. De Bruyne","M. Salah","K. Casteels","J. Castrop","B. Brobbey","M. Soulé","W. Zaïre-Emery"]},
    "PHI":  {"name": "Philadelphia Union",     "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/10739.png",                                  "players": ["A. Ramsdale","K. Walker","M. Diaby","C. Gakpo","P. Foden","A. Lafont","B. Barcola","Q. Sullivan","Iker Bravo","T. Land"]},
    "DCU":  {"name": "DC United",              "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/193.png",                                    "players": ["É. Mendy","A. Griezmann","L. Paqueta","Grimaldo","A. Hakimi","M. Rashford","A. Correa","Sávio","A. Richardson","C. Echeverri","J. Hato"]},
    "RBNY": {"name": "NY Red Bulls",           "logo": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/soccer/500/190.png&h=200&w=200",                        "players": ["Diogo Costa","Gabriel","Cristiano Ronaldo","A. Robertson","Peter","K. Mainoo","V. Carboni","A. van Axel Dongen"]},
    "CIN":  {"name": "FC Cincinnati",          "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/18267.png",                                                  "players": ["H. Lloris","Gabriel Jesús","N. Kanté","G. Xhaka","S. Haller","A. Garnacho","M. Kerkez","M. Del Blanco","Y. Bonny"]},
    "SJ":   {"name": "San Jose Earthquakes",   "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/191.png",                                                    "players": ["Alex Remiro","D. Silva","D. Rice","R. Kolo Muani","F. Wirtz","A. Güler","M. Caicedo","Newerton","E. Ferguson"]},
}

# ── Mapeo nombre de zona → código de equipo ──────────────────
ZONE_TO_CODE = {
    # WEST ZONE
    "LAFC":         "LAFC",
    "LA Galaxy":    "LA",
    "San Jose":     "SJ",
    "San Diego FC": "SDFC",
    "Portland":     "POR",
    "RSL":          "RSL",
    "Seattle":      "SEA",
    "Colorado":     "COL",
    # MIDWEST ZONE
    "Minnesota":    "MIN",
    "Sporting KC":  "SKC",
    "St. Louis":    "STL",
    "Chicago":      "CHI",
    "Cincinnati":   "CIN",
    "Columbus":     "CLB",
    # SOUTH ZONE
    "Dallas":       "DAL",
    "Austin":       "ATX",
    "Houston":      "HOU",
    "Nashville":    "NHS",
    "Charlotte":    "CLT",
    "Atlanta":      "ATL",
    "Orlando":      "ORL",
    "Miami":        "MIA",
    # NORTH ZONE
    "DC United":    "DCU",
    "Philadelphia": "PHI",
    "NYCFC":        "NYC",
    "NY Red Bulls": "RBNY",
    "New England":  "NE",
    # CANADIAN ZONE
    "Montreal":     "MTL",
    "Toronto":      "TOR",
    "Vancouver":    "VAN",
}

def get_player_photo(player_name: str, sofifa_id: int) -> str:
    safe_name = player_name.encode("ascii", "ignore").decode("ascii")
    initials  = "+".join(safe_name.split()[:2]) or "PL"
    if sofifa_id:
        s     = str(sofifa_id)
        parts = s[:-3] + "/" + s[-3:] if len(s) > 3 else s
        url   = f"https://cdn.sofifa.net/players/{parts}/25_240.png"
        return f"https://images.weserv.nl/?url={url}&w=80&h=80&fit=cover&mask=circle"
    return f"https://ui-avatars.com/api/?name={initials}&background=1a2a3a&color=f0c040&size=80&bold=true"
